apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "frontend-service"
spec:
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 30001
  type: LoadBalancer
  selector:
    app: "frontend-selector"
