apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "backend-service"
spec:
  ports:
  - name: http
    port: 33000
    protocol: TCP
    targetPort: 33000
  selector:
    app: "backend-selector"
